version: "3.9"

services:
  backend:
    build: ./backend
    container_name: archi-video-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:rw,delegated
      - ./backend/data:/app/data:rw,delegated 
    environment:
      - UVICORN_WORKERS=1
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://127.0.0.1:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend